/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewForm;

import dao.ThucPhamDao;
import helper.DataValidator;
import helper.MessageDialogHelper;
import static java.lang.String.valueOf;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import helper.Bang;
import model.ThucPham;

/**
 *
 * @author Admin
 */
public class DlogEditFood extends javax.swing.JDialog {
    private PaneAddFood panel;
    private Bang table = new Bang();
    /**
     * Creates new form DlogEditFood
     */
    public DlogEditFood(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMaTP = new javax.swing.JLabel();
        txtTenThucPham = new javax.swing.JTextField();
        txtGTDD = new javax.swing.JTextField();
        spnKhoiLuong = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        btnTang = new javax.swing.JButton();
        btnGiam = new javax.swing.JButton();
        txtGiaTien = new javax.swing.JTextField();
        pnlLTP = new javax.swing.JPanel();
        rdbRauCu = new javax.swing.JRadioButton();
        rdbThitCa = new javax.swing.JRadioButton();
        rdbHat = new javax.swing.JRadioButton();
        cbxDonVi1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        spnKhoiLuongIt = new javax.swing.JSpinner();
        cbxDonVi2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnCapNhat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(230, 236, 230));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Thông tin thực phẩm");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("Mã thực phẩm :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Tên thực phẩm :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Khối lượng cần mua : ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("Giá trị dinh dưỡng (calo/100g) :");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setText("Giá tiền cho mỗi 100g (VND) :");

        lblMaTP.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblMaTP.setText("TP-");

        txtTenThucPham.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        txtGTDD.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        spnKhoiLuong.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel14.setText("Loại thực phẩm : ");

        btnTang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Action-arrow-right-icon.png"))); // NOI18N
        btnTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangActionPerformed(evt);
            }
        });

        btnGiam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Action-arrow-left-icon.png"))); // NOI18N
        btnGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamActionPerformed(evt);
            }
        });

        txtGiaTien.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        pnlLTP.setBackground(new java.awt.Color(230, 236, 230));

        buttonGroup1.add(rdbRauCu);
        rdbRauCu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rdbRauCu.setText("Rau củ");

        buttonGroup1.add(rdbThitCa);
        rdbThitCa.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rdbThitCa.setText("Thịt cá ");
        rdbThitCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbThitCaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbHat);
        rdbHat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rdbHat.setText("Các loại hạt");

        javax.swing.GroupLayout pnlLTPLayout = new javax.swing.GroupLayout(pnlLTP);
        pnlLTP.setLayout(pnlLTPLayout);
        pnlLTPLayout.setHorizontalGroup(
            pnlLTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLTPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbRauCu)
                .addGap(33, 33, 33)
                .addComponent(rdbThitCa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(rdbHat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLTPLayout.setVerticalGroup(
            pnlLTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLTPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbRauCu)
                    .addComponent(rdbThitCa)
                    .addComponent(rdbHat))
                .addContainerGap())
        );

        cbxDonVi1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        cbxDonVi1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đơn vị", "kg", "g" }));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Khối lượng cho 1 lần mua :");

        spnKhoiLuongIt.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        cbxDonVi2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        cbxDonVi2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đơn vị", "kg", "g" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlLTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenThucPham)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblMaTP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(136, 147, Short.MAX_VALUE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGTDD)
                                    .addComponent(txtGiaTien)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spnKhoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spnKhoiLuongIt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbxDonVi2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxDonVi1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(24, 24, 24)
                        .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMaTP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenThucPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlLTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spnKhoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxDonVi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(spnKhoiLuongIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDonVi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGTDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnCapNhat.setBackground(new java.awt.Color(255, 102, 0));
        btnCapNhat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(0, 102, 102));
        btnThoat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void showThucPham(String id) throws Exception {

        ThucPhamDao dao = new ThucPhamDao();
        ThucPham tp = dao.findByID(id);
        if (tp != null) {
            lblMaTP.setText(tp.getMaThucPham());
            txtTenThucPham.setText(tp.getTenThucPham());
            rdbRauCu.setSelected(tp.getLoaiThucPham().equals(rdbRauCu.getText()) ? true : false);
            rdbThitCa.setSelected(tp.getLoaiThucPham().equals(rdbThitCa.getText()) ? true : false);
            rdbHat.setSelected(tp.getLoaiThucPham().equals(rdbHat.getText()) ? true : false);
            if (tp.getKhoiLuongTP() >= 1) {
                spnKhoiLuong.setValue((int) tp.getKhoiLuongTP());
                cbxDonVi1.setSelectedIndex(1);
            } else {
                spnKhoiLuong.setValue((int) tp.getKhoiLuongTP()*1000);
                cbxDonVi1.setSelectedIndex(2);
            }
            if (tp.getKhoiLuongIt() >= 1) {
                spnKhoiLuongIt.setValue((int) tp.getKhoiLuongIt());
                cbxDonVi2.setSelectedIndex(1);
            } else {
                spnKhoiLuongIt.setValue((int) (tp.getKhoiLuongIt()*1000));
                cbxDonVi2.setSelectedIndex(2);
            }
            txtGiaTien.setText(valueOf((int) tp.getGiaTienTP() * 1000));
            txtGTDD.setText(valueOf(tp.getGiaTriDD()));
        }
    }

    public String nextThucPham() {
        try {
            ThucPhamDao dao = new ThucPhamDao();
            ArrayList<ThucPham> list = dao.findAll();
            for (ThucPham it : list) {
                if (it.getMaThucPham().equals(lblMaTP.getText())) {
                    int i = list.indexOf(it) + 1;
                    return list.get(i).getMaThucPham();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public String backThucPham() {
        try {
            ThucPhamDao dao = new ThucPhamDao();
            ArrayList<ThucPham> list = dao.findAll();
            for (ThucPham it : list) {
                if (it.getMaThucPham().equals(lblMaTP.getText())) {
                    int i = list.indexOf(it) - 1;
                    return list.get(i).getMaThucPham();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public  String selectedTypeFood(){
        String loaiThucPham = new String("");
        if(rdbRauCu.isSelected()){
            loaiThucPham = rdbRauCu.getText();
        }
        if(rdbThitCa.isSelected()){
            loaiThucPham = rdbThitCa.getText();
        }
        if(rdbHat.isSelected()){
            loaiThucPham = rdbHat.getText();
        }
        return loaiThucPham;
    }
    
    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        panel = new PaneAddFood();
        StringBuilder sb = new StringBuilder();
        StringBuilder str = new StringBuilder();
        DataValidator.validateEmpty(txtTenThucPham, sb, "\t- Tên thực phẩm!");
        DataValidator.validateEmpty(spnKhoiLuong, sb, "\t- Khối lượng cần mua!");
        DataValidator.validateEmpty(cbxDonVi1, sb, "\t- Đơn vị khối lượng mua!");
        DataValidator.validateEmpty(txtGiaTien, sb, "\t- Giá tiền cho mỗi 100g thực phẩm!");
        if(selectedTypeFood().equals("")){
            sb.append("\t- Loại thực phẩm!").append("\n");
            pnlLTP.setBackground(new java.awt.Color(255, 255, 0));
            pnlLTP.requestFocus();
        }else{
            pnlLTP.setBackground(new java.awt.Color(230, 236, 230));
        }
        DataValidator.validateEmpty(txtGTDD, sb, "\t- Giá trị dinh dưỡng cho 100g!");
       if(Integer.parseInt(txtGiaTien.getText()) <= 1000 && txtGiaTien.getText().equals("") ){
            DataValidator.isNumberic(txtGiaTien, str, "\t- Giá tiền phải nhập số và có giá trị > 1000 VND.");
        }
        if (txtGTDD.getText().equals("")) {
            DataValidator.isNumberic(txtGTDD, str, "\t- Giá trị dinh dưỡng phải nhập số.");
        }
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(this, "Bạn chưa nhập vào đầy đủ (hoặc không đúng) thông tin của thực phẩm:\n" + sb.toString() + str.toString(), "Lỗi");
            return;
        }
        
        try{
            ThucPham tp = new ThucPham();
            tp.setMaThucPham(lblMaTP.getText());
            tp.setTenThucPham(table.firstUpcase(txtTenThucPham.getText()));
            if (cbxDonVi1.getSelectedIndex() == 1) {
                tp.setKhoiLuongTP((float)((int) spnKhoiLuong.getValue()));
            } else {
                tp.setKhoiLuongTP((float)((int) spnKhoiLuong.getValue())/1000);
            }
            if (cbxDonVi2.getSelectedIndex() == 1) {
                tp.setKhoiLuongIt((float)((int) spnKhoiLuongIt.getValue()));
            } else {
                tp.setKhoiLuongIt((float)((int) spnKhoiLuongIt.getValue())/1000);
            }
            tp.setLoaiThucPham(selectedTypeFood());
            int giaTien = (int) (Long.parseLong(txtGiaTien.getText()) / 1000) ;
            tp.setGiaTienTP(giaTien);
            tp.setGiaTriDD(Integer.parseInt(txtGTDD.getText()));
            tp.setDonGia((float)tp.getGiaTriDD() / (float)tp.getGiaTienTP());
            
            ThucPhamDao dao = new ThucPhamDao();
            if(dao.findByID(tp.getMaThucPham()) == null){
                MessageDialogHelper.showWarningDialog(this, "Bạn không thể cập nhật bởi vì thực phẩm\n"+"này không có trong danh sách.\n"+"", "Cảnh báo");
                if(MessageDialogHelper.showConfirmDialog(this, "Để tiếp tục bạn có thể lưu lại thực phẩm này?", "Câu hỏi") == JOptionPane.YES_OPTION){
                     tp.setMaThucPham(panel.createMa());
                    if(dao.insert(tp)){
                        MessageDialogHelper.showMessageDialog(this, "Thực phẩm đã được lưu thành công.", "Thông báo");
                    } else {
                        MessageDialogHelper.showMessageDialog(this, "Thực phẩm không được lưu!", "Thông báo");
                    }
                }
                return;
            }
            if(dao.update(tp)){
                MessageDialogHelper.showMessageDialog(this, "Thực phẩm đã được cập nhật thành công.", "Thông báo");
            }else{
                MessageDialogHelper.showMessageDialog(this, "Thực phẩm không được cập nhật!", "Thông báo");
            }
        }catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog( this, "Đã xảy ra lôi khi cập nhật thực phẩm!\nBạn hãy thử cập nhật lại.","Lỗi");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangActionPerformed
        try {
            showThucPham(nextThucPham());
        } catch (Exception ex) {
            Logger.getLogger(DlogSeeFood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTangActionPerformed

    private void btnGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamActionPerformed
        try {
            showThucPham(backThucPham());
        } catch (Exception ex) {
            Logger.getLogger(DlogSeeFood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGiamActionPerformed

    private void rdbThitCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbThitCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbThitCaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlogEditFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlogEditFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlogEditFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlogEditFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlogEditFood dialog = new DlogEditFood(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnGiam;
    private javax.swing.JButton btnTang;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxDonVi1;
    private javax.swing.JComboBox<String> cbxDonVi2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMaTP;
    private javax.swing.JPanel pnlLTP;
    private javax.swing.JRadioButton rdbHat;
    private javax.swing.JRadioButton rdbRauCu;
    private javax.swing.JRadioButton rdbThitCa;
    private javax.swing.JSpinner spnKhoiLuong;
    private javax.swing.JSpinner spnKhoiLuongIt;
    private javax.swing.JTextField txtGTDD;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtTenThucPham;
    // End of variables declaration//GEN-END:variables
}
