/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewForm;

import dao.ThucPhamDao;
import helper.MessageDialogHelper;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import helper.Bang;
import model.ThucPham;

/**
 *
 * @author Admin
 */
public class DlogChooseFood extends javax.swing.JDialog {

    private FrmMain home;
    private Bang table = new Bang();
    private PaneCreateCart panel;
    ArrayList<String> list = new ArrayList<>();

    /**
     * Creates new form DialogChonThucPham
     */
    public DlogChooseFood(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        home = (FrmMain) parent;
        table.initTable1(tblDsThucPham);
        table.loadDataToTable(jPanel1);
        table.tableModelChooe(tblDsThucPham);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDsThucPham = new javax.swing.JTable();
        btnThemVaoGio = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chọn thực phẩm từ danh sách");

        jPanel1.setBackground(new java.awt.Color(230, 236, 230));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Bạn hãy chọn các thực phẩm bên dưới:");

        tblDsThucPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã thực phẩm", "Tên thực phẩm", "Loại thực phẩm", "Khối lượng (g)", "", "Giá trị dinh dưỡng (calo/100g)", "Giá tiền mỗi 100g (VND)"
            }
        ));
        tblDsThucPham.setGridColor(new java.awt.Color(153, 153, 153));
        tblDsThucPham.setShowGrid(true);
        tblDsThucPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblDsThucPhamKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblDsThucPham);
        if (tblDsThucPham.getColumnModel().getColumnCount() > 0) {
            tblDsThucPham.getColumnModel().getColumn(0).setMinWidth(60);
            tblDsThucPham.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblDsThucPham.getColumnModel().getColumn(0).setMaxWidth(60);
            tblDsThucPham.getColumnModel().getColumn(1).setMinWidth(110);
            tblDsThucPham.getColumnModel().getColumn(1).setMaxWidth(110);
            tblDsThucPham.getColumnModel().getColumn(2).setMinWidth(160);
            tblDsThucPham.getColumnModel().getColumn(2).setMaxWidth(160);
            tblDsThucPham.getColumnModel().getColumn(3).setMinWidth(120);
            tblDsThucPham.getColumnModel().getColumn(3).setMaxWidth(120);
            tblDsThucPham.getColumnModel().getColumn(4).setMinWidth(130);
            tblDsThucPham.getColumnModel().getColumn(4).setMaxWidth(130);
            tblDsThucPham.getColumnModel().getColumn(5).setMinWidth(140);
            tblDsThucPham.getColumnModel().getColumn(5).setMaxWidth(140);
            tblDsThucPham.getColumnModel().getColumn(6).setMinWidth(200);
            tblDsThucPham.getColumnModel().getColumn(6).setMaxWidth(200);
            tblDsThucPham.getColumnModel().getColumn(7).setMinWidth(170);
            tblDsThucPham.getColumnModel().getColumn(7).setMaxWidth(170);
        }

        btnThemVaoGio.setBackground(new java.awt.Color(0, 0, 204));
        btnThemVaoGio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThemVaoGio.setForeground(new java.awt.Color(255, 255, 255));
        btnThemVaoGio.setText("Thêm vào giỏ");
        btnThemVaoGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoGioActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(0, 102, 102));
        btnThoat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(230, 236, 230));
        btnXoa.setForeground(new java.awt.Color(255, 0, 0));
        btnXoa.setText("Bỏ chọn");
        btnXoa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Danh sách thực phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemVaoGio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(299, 299, 299))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXoa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemVaoGio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemVaoGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoGioActionPerformed
        try {
            int row[] = tblDsThucPham.getSelectedRows();

            try {
                for (int i = 0; i < row.length; i++) {
                    String id = (String) tblDsThucPham.getValueAt(row[i], 1);
                    list.add(id);
                }
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
                MessageDialogHelper.showErrorDialog(this, "Đã xảy ra lôi khi thêm thực phẩm!\nBạn hãy thử thêm lại.", "Lỗi");
            }
        } catch (Exception ex) {
            Logger.getLogger(PaneListFood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemVaoGioActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        tblDsThucPham.clearSelection();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblDsThucPhamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDsThucPhamKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            try {
                int row[] = tblDsThucPham.getSelectedRows();

                try {
                    for (int i = 0; i < row.length; i++) {
                        String id = (String) tblDsThucPham.getValueAt(row[i], 1);
                        list.add(id);
                    }
                    this.dispose();
                } catch (Exception e) {
                    e.printStackTrace();
                    MessageDialogHelper.showErrorDialog(this, "Đã xảy ra lôi khi thêm thực phẩm!\nBạn hãy thử thêm lại.", "Lỗi");
                }
            } catch (Exception ex) {
                Logger.getLogger(PaneListFood.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblDsThucPhamKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlogChooseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlogChooseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlogChooseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlogChooseFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlogChooseFood dialog = new DlogChooseFood(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemVaoGio;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDsThucPham;
    // End of variables declaration//GEN-END:variables
}
