/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewForm;

import dao.GioHangDao;
import dao.KetQuaDao;
import dao.ThucPhamDao;
import helper.MessageDialogHelper;
import java.awt.Dimension;
import static java.lang.String.valueOf;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import helper.Bang;
import model.GioHang;
import model.KetQua;
import model.PhuongAn;
import model.ThucPham;

/**
 *
 * @author Admin
 */
public class DlogSeeCart extends javax.swing.JDialog {

    ArrayList<KetQua> listGioHang = new ArrayList<>();
    private Bang table = new Bang();

    /**
     * Creates new form DialogSeeCart
     */
    public DlogSeeCart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        table.initTableKetQuaGH(tblGioHang);
        table.tableModelSeeKQ(tblGioHang);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        lblMaGioHang = new javax.swing.JLabel();
        lblTenGioHang = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        lblSoTienMua = new javax.swing.JLabel();
        lblSTConLai = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaGhiChu = new javax.swing.JTextArea();
        lblTongKhoiLuong = new javax.swing.JLabel();
        lblTongGTDD = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnGiam = new javax.swing.JButton();
        btnTang = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 244, 228));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Thông tin giỏ hàng");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(170, 137, 35));
        jLabel2.setText("Mã giỏ hàng :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(170, 137, 35));
        jLabel3.setText("Tên giỏ hàng :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(170, 137, 35));
        jLabel4.setText("Ngày tạo :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(170, 137, 35));
        jLabel5.setText("Số tiền cần mua :");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(170, 137, 35));
        jLabel6.setText("Ghi chú : ");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(170, 137, 35));
        jLabel7.setText("Số tiền còn lại : ");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("Tổng khối lượng: ");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setText("Tổng giá trị dinh dưỡng:");

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "", "Title 7", "Title 8", "Title 9"
            }
        ));
        tblGioHang.setGridColor(new java.awt.Color(153, 153, 153));
        tblGioHang.setShowGrid(true);
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGioHang);
        if (tblGioHang.getColumnModel().getColumnCount() > 0) {
            tblGioHang.getColumnModel().getColumn(0).setMinWidth(40);
            tblGioHang.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblGioHang.getColumnModel().getColumn(0).setMaxWidth(40);
            tblGioHang.getColumnModel().getColumn(1).setMinWidth(90);
            tblGioHang.getColumnModel().getColumn(1).setMaxWidth(90);
            tblGioHang.getColumnModel().getColumn(2).setMinWidth(180);
            tblGioHang.getColumnModel().getColumn(2).setMaxWidth(180);
            tblGioHang.getColumnModel().getColumn(3).setMinWidth(110);
            tblGioHang.getColumnModel().getColumn(3).setMaxWidth(110);
            tblGioHang.getColumnModel().getColumn(4).setMinWidth(110);
            tblGioHang.getColumnModel().getColumn(4).setMaxWidth(100);
            tblGioHang.getColumnModel().getColumn(5).setMinWidth(110);
            tblGioHang.getColumnModel().getColumn(5).setMaxWidth(110);
            tblGioHang.getColumnModel().getColumn(6).setMinWidth(150);
            tblGioHang.getColumnModel().getColumn(6).setMaxWidth(150);
            tblGioHang.getColumnModel().getColumn(7).setMinWidth(150);
            tblGioHang.getColumnModel().getColumn(7).setMaxWidth(150);
            tblGioHang.getColumnModel().getColumn(8).setMinWidth(130);
            tblGioHang.getColumnModel().getColumn(8).setMaxWidth(130);
        }

        lblMaGioHang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblMaGioHang.setForeground(new java.awt.Color(0, 102, 51));
        lblMaGioHang.setText("jLabel10");

        lblTenGioHang.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblTenGioHang.setForeground(new java.awt.Color(0, 102, 51));
        lblTenGioHang.setText("jLabel11");

        lblNgayTao.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblNgayTao.setForeground(new java.awt.Color(0, 102, 51));
        lblNgayTao.setText("jLabel12");

        lblSoTienMua.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSoTienMua.setForeground(new java.awt.Color(0, 102, 51));
        lblSoTienMua.setText("jLabel13");

        lblSTConLai.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSTConLai.setForeground(new java.awt.Color(0, 102, 51));
        lblSTConLai.setText("jLabel14");

        txaGhiChu.setColumns(20);
        txaGhiChu.setRows(5);
        jScrollPane2.setViewportView(txaGhiChu);

        lblTongKhoiLuong.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblTongKhoiLuong.setForeground(new java.awt.Color(255, 0, 0));
        lblTongKhoiLuong.setText("jLabel14");

        lblTongGTDD.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        lblTongGTDD.setForeground(new java.awt.Color(255, 0, 0));
        lblTongGTDD.setText("jLabel14");

        btnXoa.setBackground(new java.awt.Color(255, 0, 51));
        btnXoa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(0, 153, 153));
        btnThoat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnGiam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Action-arrow-left-icon.png"))); // NOI18N
        btnGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamActionPerformed(evt);
            }
        });

        btnTang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Action-arrow-right-icon.png"))); // NOI18N
        btnTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSoTienMua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMaGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSTConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTenGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(256, 256, 256))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1072, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblTongKhoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblTongGTDD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblMaGioHang)
                    .addComponent(lblTenGioHang)
                    .addComponent(lblNgayTao))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(lblSoTienMua)
                            .addComponent(lblSTConLai)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTongKhoiLuong)
                    .addComponent(jLabel9)
                    .addComponent(lblTongGTDD))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamActionPerformed
        try {
            showGioHang(backGioHang());
        } catch (Exception ex) {
            Logger.getLogger(DlogSeeCart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGiamActionPerformed

    private void btnTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangActionPerformed

        try {
            showGioHang(nextGioHang());
        } catch (Exception ex) {
            Logger.getLogger(DlogSeeCart.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnTangActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (MessageDialogHelper.showConfirmDialog(this, "Bạn có muốn xóa thực phẩm này hay không?", "Câu hỏi") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            GioHang tp = new GioHang();
            GioHangDao dao = new GioHangDao();
            String id = new String();
            int sus = 0, fail = 0, a = 0;
            id = nextGioHang();
            if (id == null) {
                id = backGioHang();
            }
            String ma = lblMaGioHang.getText();
            KetQuaDao daokq = new KetQuaDao();
            if (daokq.deleteGioHang(ma)) {
                a++;
            }
            if (dao.delete(ma)) {
                MessageDialogHelper.showMessageDialog(this, "Thực phẩm đã được xóa thành công.", "Thông báo");
                if (id == null) {
                    this.dispose();
                }
                try {
                    showGioHang(id);
                } catch (Exception ex) {
                    Logger.getLogger(DlogSeeFood.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                MessageDialogHelper.showMessageDialog(this, "Thực phẩm không được xóa!", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, "Đã xảy ra lôi khi xóa thực phẩm!\nBạn hãy thử xóa lại.", "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
//        int row = tblGioHang.getSelectedRow();
//        String id = (String) tblGioHang.getValueAt(row, 1);
//        String ma = lblMaGioHang.getText();
//        PaneFoodDetails panel = new PaneFoodDetails();
//
//        pnlDetails.removeAll();
//        try {
//            panel.showGioHang(ma, id);
//        } catch (Exception ex) {
//            Logger.getLogger(DlogSeeCart.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        panel.setPreferredSize(new Dimension(1122, 134));
//        pnlDetails.add(panel);
//        pnlDetails.updateUI();

    }//GEN-LAST:event_tblGioHangMouseClicked

//    public void showThucPham(String maThucPham) throws Exception{
//        for (int i = 0; i < listGioHang.size(); i++){
//        if(listGioHang.get(i).equals(maThucPham)){
//            lblTenThucPham.setText(listGioHang.get(i).getTenThucPham());
//            lblKhoiLuog.setText(String.format("%.1f", (float)listGioHang.get(i).getPhuongAn()) + " (kg)");
//            lblGTDD.setText(valueOf(listGioHang.get(i).getGiaTriDD()*listGioHang.get(i).getPhuongAn()) +" (calo)");
//            lblSoTien.setText(valueOf(listGioHang.get(i).getGiaTienTP()*listGioHang.get(i).getPhuongAn()*1000) +" (VND)");
//        } else MessageDialogHelper.showErrorDialog(this, "Đã xảy ra lôi khi xóa thực phẩm!\nBạn hãy thử xóa lại.", "Lỗi");
//        }
//    }
    public String nextGioHang() {
        try {
            GioHangDao dao = new GioHangDao();
            ArrayList<GioHang> list = dao.findAll();
            for (GioHang it : list) {
                if (it.getMaGioHang().equals(lblMaGioHang.getText())) {
                    int i = list.indexOf(it) + 1;
                    if (list.size() != i) {
                        return list.get(i).getMaGioHang();
                    } else {
                        return null;
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public String backGioHang() {
        try {
            GioHangDao dao = new GioHangDao();
            ArrayList<GioHang> list = dao.findAll();
            for (GioHang it : list) {
                if (it.getMaGioHang().equals(lblMaGioHang.getText())) {
                    int i = list.indexOf(it) - 1;
                    if (i != -1) {
                        return list.get(i).getMaGioHang();
                    } else {
                        return null;
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public void showGioHang(String id) throws Exception {

        GioHangDao dao = new GioHangDao();
        GioHang gh = dao.findByID(id);
        if (gh != null) {
            lblMaGioHang.setText(gh.getMaGioHang());
            lblTenGioHang.setText(gh.getTenGioHang());
            lblNgayTao.setText(gh.getNgayTao());
            lblSoTienMua.setText(valueOf(gh.getSoTienMua() * 1000));
            txaGhiChu.setText("(không có)");
        }
        ArrayList<KetQua> list = new ArrayList<>();

        KetQuaDao daokq = new KetQuaDao();
        list = daokq.findAll();
        float tongKhoiLuong = 0;
        for (int i = 0; i < list.size(); i++) {
            if (list.get(i).getMaGioHang().equals(id)) {
                listGioHang.add(list.get(i));
                tongKhoiLuong = tongKhoiLuong +  list.get(i).getPhuongAn();
            }
        }
        lblSTConLai.setText(valueOf((int)(gh.getSoTienCL() * 1000)) + " (VND)");
        lblTongKhoiLuong.setText(valueOf(tongKhoiLuong) + " (kg)");
        lblTongGTDD.setText(valueOf(gh.getGiaTriDD()) + " (calo)");
        table.loadDataToTableKetQuaGH(jPanel1, listGioHang);
        table.tableModelSeeKQ(tblGioHang);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlogSeeCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlogSeeCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlogSeeCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlogSeeCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlogSeeCart dialog = new DlogSeeCart(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiam;
    private javax.swing.JButton btnTang;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaGioHang;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblSTConLai;
    private javax.swing.JLabel lblSoTienMua;
    private javax.swing.JLabel lblTenGioHang;
    private javax.swing.JLabel lblTongGTDD;
    private javax.swing.JLabel lblTongKhoiLuong;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTextArea txaGhiChu;
    // End of variables declaration//GEN-END:variables
}
