/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewForm;

import dao.ThucPhamDao;
import helper.MessageDialogHelper;
import static java.lang.String.valueOf;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.ThucPham;

/**
 *
 * @author Admin
 */
public class DlogSeeFood extends javax.swing.JDialog {

    /**
     * Creates new form DlogThucPham
     */
    public DlogSeeFood(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
//        showThucPham(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblMaTP = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdbRauCu = new javax.swing.JRadioButton();
        rdbThitCa = new javax.swing.JRadioButton();
        rdbHat = new javax.swing.JRadioButton();
        btnTang = new javax.swing.JButton();
        btnGiam = new javax.swing.JButton();
        lblTenThucPham = new javax.swing.JLabel();
        lblKhoiLuong = new javax.swing.JLabel();
        lblGTDD = new javax.swing.JLabel();
        lblGiaTien = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblKhoiLuongIt = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thực phẩm");

        jPanel2.setBackground(new java.awt.Color(230, 236, 230));

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Thông tin thực phẩm");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setText("Mã thực phẩm :");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setText("Tên thực phẩm :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setText("Khối lượng cần mua : ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel5.setText("Giá trị dinh dưỡng (calo/100g) :");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel6.setText("Giá tiền cho mỗi 100g (VND) :");

        lblMaTP.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblMaTP.setForeground(new java.awt.Color(0, 102, 102));
        lblMaTP.setText("TP-");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel14.setText("Loại thực phẩm : ");

        buttonGroup1.add(rdbRauCu);
        rdbRauCu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rdbRauCu.setText("Rau củ");

        buttonGroup1.add(rdbThitCa);
        rdbThitCa.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rdbThitCa.setText("Thịt cá ");

        buttonGroup1.add(rdbHat);
        rdbHat.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        rdbHat.setText("Các loại hạt");

        btnTang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Action-arrow-right-icon.png"))); // NOI18N
        btnTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangActionPerformed(evt);
            }
        });

        btnGiam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Action-arrow-left-icon.png"))); // NOI18N
        btnGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamActionPerformed(evt);
            }
        });

        lblTenThucPham.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTenThucPham.setForeground(new java.awt.Color(153, 102, 0));
        lblTenThucPham.setText("jLabel7");

        lblKhoiLuong.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblKhoiLuong.setForeground(new java.awt.Color(153, 102, 0));
        lblKhoiLuong.setText("jLabel8");

        lblGTDD.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblGTDD.setForeground(new java.awt.Color(153, 102, 0));
        lblGTDD.setText("jLabel9");

        lblGiaTien.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblGiaTien.setForeground(new java.awt.Color(153, 102, 0));
        lblGiaTien.setText("jLabel10");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel7.setText("Khối lượng cho 1 lần mua :");

        lblKhoiLuongIt.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblKhoiLuongIt.setForeground(new java.awt.Color(153, 102, 0));
        lblKhoiLuongIt.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMaTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(rdbRauCu)
                                                        .addGap(36, 36, 36)
                                                        .addComponent(rdbThitCa)
                                                        .addGap(26, 26, 26)
                                                        .addComponent(rdbHat))
                                                    .addComponent(lblTenThucPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(lblKhoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblGiaTien, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(lblGTDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblKhoiLuongIt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)))
                .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMaTP, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblTenThucPham))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rdbRauCu)
                    .addComponent(rdbThitCa)
                    .addComponent(rdbHat))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblKhoiLuong))))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblKhoiLuongIt))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblGTDD))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblGiaTien))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnXoa.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(0, 102, 102));
        btnThoat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showThucPham(String id) throws Exception {

        ThucPhamDao dao = new ThucPhamDao();
        ThucPham tp = dao.findByID(id);
        if (tp != null) {
            lblMaTP.setText(tp.getMaThucPham());
            lblTenThucPham.setText(tp.getTenThucPham());
            rdbRauCu.setSelected(tp.getLoaiThucPham().equals(rdbRauCu.getText()) ? true : false);
            rdbThitCa.setSelected(tp.getLoaiThucPham().equals(rdbThitCa.getText()) ? true : false);
            rdbHat.setSelected(tp.getLoaiThucPham().equals(rdbHat.getText()) ? true : false);
            if (tp.getKhoiLuongTP() >= 1) {
                lblKhoiLuong.setText(valueOf(tp.getKhoiLuongTP()) + " (kg)");
            } else {
                lblKhoiLuong.setText(valueOf((int)(tp.getKhoiLuongTP()*1000)) + " (g)");
            }
            if (tp.getKhoiLuongIt() >= 1) {
                lblKhoiLuongIt.setText(valueOf(tp.getKhoiLuongIt()) + " (kg)");
            } else {
                lblKhoiLuongIt.setText(valueOf((int)(tp.getKhoiLuongIt()*1000)) + " (g)");
            }
            lblGiaTien.setText(valueOf((int) tp.getGiaTienTP() * 1000) + " VND");
            lblGTDD.setText(valueOf(tp.getGiaTriDD()) + " calo");
        }
    }

    public String nextThucPham() {
        try {
            ThucPhamDao dao = new ThucPhamDao();
            ArrayList<ThucPham> list = dao.findAll();
            for (ThucPham it : list) {
                if (it.getMaThucPham().equals(lblMaTP.getText())) {
                    int i = list.indexOf(it) + 1;
                    return list.get(i).getMaThucPham();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public String backThucPham() {
        try {
            ThucPhamDao dao = new ThucPhamDao();
            ArrayList<ThucPham> list = dao.findAll();
            for (ThucPham it : list) {
                if (it.getMaThucPham().equals(lblMaTP.getText())) {
                    int i = list.indexOf(it) - 1;
                    return list.get(i).getMaThucPham();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (MessageDialogHelper.showConfirmDialog(this, "Bạn có muốn xóa thực phẩm này hay không?", "Câu hỏi") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            ThucPham tp = new ThucPham();
            ThucPhamDao dao = new ThucPhamDao();
            if (dao.findByID(lblMaTP.getText()) == null) {
                MessageDialogHelper.showWarningDialog(this, "Bạn không thể xóa bởi vì thực phẩm\n" + "này không có trong danh sách.\n" + "", "Cảnh báo");
                return;
            }
            String id = new String();
            id = nextThucPham();
            if (id == null) {
                id = backThucPham();
            }
            if (dao.delete(lblMaTP.getText())) {
                MessageDialogHelper.showMessageDialog(this, "Thực phẩm đã được xóa thành công.", "Thông báo");
                if (id == null) {
                    setVisible(false);
                    this.dispose();
                }
                try {
                    showThucPham(id);
                } catch (Exception ex) {
                    Logger.getLogger(DlogSeeFood.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                MessageDialogHelper.showMessageDialog(this, "Thực phẩm không được xóa!", "Thông báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, "Đã xảy ra lôi khi xóa thực phẩm!\nBạn hãy thử xóa lại.", "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangActionPerformed
        try {
            showThucPham(nextThucPham());
        } catch (Exception ex) {
            Logger.getLogger(DlogSeeFood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTangActionPerformed

    private void btnGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiamActionPerformed
        try {
            showThucPham(backThucPham());
        } catch (Exception ex) {
            Logger.getLogger(DlogSeeFood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGiamActionPerformed

    public JButton getBtnThoat() {
        return btnThoat;
    }

    public void setBtnThoat(JButton btnThoat) {
        this.btnThoat = btnThoat;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlogSeeFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlogSeeFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlogSeeFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlogSeeFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlogSeeFood dialog = null;
                try {
                    dialog = new DlogSeeFood(new javax.swing.JFrame(), true);
                } catch (Exception ex) {
                    Logger.getLogger(DlogSeeFood.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiam;
    private javax.swing.JButton btnTang;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGTDD;
    private javax.swing.JLabel lblGiaTien;
    private javax.swing.JLabel lblKhoiLuong;
    private javax.swing.JLabel lblKhoiLuongIt;
    private javax.swing.JLabel lblMaTP;
    private javax.swing.JLabel lblTenThucPham;
    private javax.swing.JRadioButton rdbHat;
    private javax.swing.JRadioButton rdbRauCu;
    private javax.swing.JRadioButton rdbThitCa;
    // End of variables declaration//GEN-END:variables

    Object setBtnCapNhatTP() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
