/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewForm;

import helper.MessageDialogHelper;
import java.awt.ComponentOrientation;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Panel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import static java.lang.String.valueOf;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.Timer;
import helper.CloseTab;

/**
 *
 * @author Admin
 */
public class FrmMain extends javax.swing.JFrame {

    static javax.swing.JPanel pnlMain;
    static ArrayList<javax.swing.JPanel> listPanel;
    static ArrayList<String> listIndex;
    private JPanel childPanel;
    JPanel pnlNow;
    static int now = 1, back = 1, indexList = -1;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() throws Exception {
        initComponents();
        initUI();
        createGUI();
        createListPanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        mitHome = new javax.swing.JMenuItem();
        mitFind = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitAddFood = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mitListFood = new javax.swing.JMenuItem();
        menuCart = new javax.swing.JMenu();
        mitAddCart = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        icon = new javax.swing.JMenuItem();
        mitListCart = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitHelp = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mitExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/version-icon.png"))); // NOI18N
        jLabel4.setText("Version 1.0");

        lblTime.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Clock-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 959, Short.MAX_VALUE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(116, 188, 140));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_home.png"))); // NOI18N
        home.setText("Trang chủ ");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        mitHome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mitHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house-icon.png"))); // NOI18N
        mitHome.setText("Về Trang Chủ     ");
        mitHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitHomeActionPerformed(evt);
            }
        });
        home.add(mitHome);

        mitFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitFind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green-search-icon.png"))); // NOI18N
        mitFind.setText("Tìm kiếm");
        mitFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitFindActionPerformed(evt);
            }
        });
        home.add(mitFind);

        jMenuBar1.add(home);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_food.png"))); // NOI18N
        jMenu2.setText("Thực phẩm");

        mitAddFood.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitAddFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_newfood1.png"))); // NOI18N
        mitAddFood.setText("Thêm mới");
        mitAddFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAddFoodActionPerformed(evt);
            }
        });
        jMenu2.add(mitAddFood);
        jMenu2.add(jSeparator1);

        mitListFood.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mitListFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_listfood.png"))); // NOI18N
        mitListFood.setText("Xem danh sách ");
        mitListFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitListFoodActionPerformed(evt);
            }
        });
        jMenu2.add(mitListFood);

        jMenuBar1.add(jMenu2);

        menuCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_cart.png"))); // NOI18N
        menuCart.setText("Giỏ hàng");

        mitAddCart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitAddCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_newcart.png"))); // NOI18N
        mitAddCart.setText("Tạo mới");
        mitAddCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAddCartActionPerformed(evt);
            }
        });
        menuCart.add(mitAddCart);
        menuCart.add(jSeparator3);

        icon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/opencart-icon.png"))); // NOI18N
        icon.setText("Mở giỏ hàng");
        icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iconActionPerformed(evt);
            }
        });
        menuCart.add(icon);

        mitListCart.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitListCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_listcart.png"))); // NOI18N
        mitListCart.setText("Xem danh sách ");
        mitListCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitListCartActionPerformed(evt);
            }
        });
        menuCart.add(mitListCart);

        jMenuBar1.add(menuCart);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_ques.png"))); // NOI18N
        jMenu4.setText("Trợ giúp");

        mitHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_help.png"))); // NOI18N
        mitHelp.setText("Hướng dẫn");
        mitHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitHelpActionPerformed(evt);
            }
        });
        jMenu4.add(mitHelp);
        jMenu4.add(jSeparator2);

        mitExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mitExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_exit.png"))); // NOI18N
        mitExit.setText("Thoát");
        mitExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitExitActionPerformed(evt);
            }
        });
        jMenu4.add(mitExit);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   private void initUI() {
        setTitle("Ứng dụng thuật toán tối ưu vào bài toán cái balo");
        setSize(1460, 1000);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat(" HH:mm a     E, dd/MM/yyyy");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblTime.setText(format.format(new Date()));
            }
        }).start();
        this.openWelcome();
    }

    public void createListPanel() throws Exception {
        listPanel = new ArrayList<>();
        listIndex = new ArrayList<>();
        listIndex.add("1");
        listPanel.add(new PaneSearch());
        listPanel.add(new PaneHome());
        listPanel.add(new PaneAddFood());
        listPanel.add(new PaneListFood());
        listPanel.add(new PaneCreateCart());
        listPanel.add(new PaneListCart());
    }

    void openWelcome() {
        new DlogWelcom(this, true).setVisible(true);
    }

    public void createGUI() {
        createJPane();
        add(pnlMain);
    }

    private PaneHome createJPanel() {
        PaneHome panel = new PaneHome();
        return panel;

    }

    public JPanel getPnlMain() {
        return pnlMain;
    }

    private void createJPane() {
        pnlMain = new javax.swing.JPanel();
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMain.add(createJPanel());
    }

    public void showPanel(int a) {
        pnlMain.removeAll();
        if (a == 2 || a == 3 || a == 5) {
            if (a == 2) {
                PaneAddFood panel = (PaneAddFood) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }
            if (a == 3) {
                PaneListFood panel = (PaneListFood) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }
            if (a == 5) {
                PaneListCart panel = (PaneListCart) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }

        } else {
            pnlMain.add(listPanel.get(a));
        }

        pnlMain.updateUI();
        if (a == 1) {
            indexList = 0;
            listIndex.removeAll(listIndex);
            listIndex.add(valueOf(a));
        } else {
            if (Integer.parseInt(listIndex.get(listIndex.size() - 1)) != a) {
                listIndex.add(valueOf(a));
                indexList = listIndex.size() - 1;
            }
        }
        now = a;
    }

    private void mitHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitHomeActionPerformed
        showPanel(1);
    }//GEN-LAST:event_mitHomeActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed

    }//GEN-LAST:event_homeActionPerformed

    private void mitAddFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAddFoodActionPerformed
        showPanel(2);
    }//GEN-LAST:event_mitAddFoodActionPerformed

    private void mitListFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitListFoodActionPerformed
        showPanel(3);
    }//GEN-LAST:event_mitListFoodActionPerformed

    private void mitAddCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAddCartActionPerformed
        try {
            showPanel(4);
        } catch (Exception ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mitAddCartActionPerformed

    private void iconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iconActionPerformed

    private void mitListCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitListCartActionPerformed
        showPanel(5);
    }//GEN-LAST:event_mitListCartActionPerformed

    private void mitHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitHelpActionPerformed
       try{
            File f = new File("C:\\Users\\Admin\\Documents\\help.pdf");
            Desktop.getDesktop().open(f);
        }catch (Exception e) {
            e.printStackTrace();           
        }
    }//GEN-LAST:event_mitHelpActionPerformed

    private void mitExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitExitActionPerformed

    private void mitFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitFindActionPerformed
        if (now > 1) {
            DlogFind find = new DlogFind(this, true);
            find.setVisible(true);
        }
    }//GEN-LAST:event_mitFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmMain().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu home;
    private javax.swing.JMenuItem icon;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblTime;
    private javax.swing.JMenu menuCart;
    private javax.swing.JMenuItem mitAddCart;
    private javax.swing.JMenuItem mitAddFood;
    private javax.swing.JMenuItem mitExit;
    private javax.swing.JMenuItem mitFind;
    private javax.swing.JMenuItem mitHelp;
    private javax.swing.JMenuItem mitHome;
    private javax.swing.JMenuItem mitListCart;
    private javax.swing.JMenuItem mitListFood;
    // End of variables declaration//GEN-END:variables
}
