/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewForm;

import dao.GioHangDao;
import dao.ThucPhamDao;
import helper.MessageDialogHelper;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import static java.lang.String.valueOf;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import model.GioHang;
import model.ThucPham;
import static viewForm.FrmMain.indexList;
import static viewForm.FrmMain.listIndex;
import static viewForm.FrmMain.listPanel;
import static viewForm.FrmMain.pnlMain;
import static viewForm.FrmMain.now;
import static viewForm.FrmMain.pnlMain;

/**
 *
 * @author Admin
 */
public class PaneHome extends javax.swing.JPanel {

    private JPanel childPanel;

    /**
     * Creates new form PanelHome
     */
    public PaneHome() {
        initComponents();
        defaultLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtSeach = new javax.swing.JTextField();
        btnSeach1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        pnlAddFood = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/main/resources/images/taothucphammoi.gif");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel23 = new javax.swing.JLabel();
        pnlAddCart = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/main/resources/images/taogiohang.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel24 = new javax.swing.JLabel();
        pnlListFood = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/main/resources/images/dsthucpham.jpg");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel25 = new javax.swing.JLabel();
        pnlListCart1 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("src/main/resources/images/dsthucpham.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHelp1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(230, 236, 230));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Nhập từ khóa :");

        txtSeach.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtSeach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSeachKeyPressed(evt);
            }
        });

        btnSeach1.setBackground(new java.awt.Color(149, 204, 149));
        btnSeach1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnSeach1.setForeground(new java.awt.Color(0, 102, 0));
        btnSeach1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green-search-icon.png"))); // NOI18N
        btnSeach1.setText("Tìm kiếm");
        btnSeach1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSeach1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSeach1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSeach1MouseExited(evt);
            }
        });
        btnSeach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeach1ActionPerformed(evt);
            }
        });

        pnlAddFood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        pnlAddFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddFoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddFoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddFoodMouseExited(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 255));
        jLabel23.setText("Thêm Thực Phẩm Mới");

        javax.swing.GroupLayout pnlAddFoodLayout = new javax.swing.GroupLayout(pnlAddFood);
        pnlAddFood.setLayout(pnlAddFoodLayout);
        pnlAddFoodLayout.setHorizontalGroup(
            pnlAddFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddFoodLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        pnlAddFoodLayout.setVerticalGroup(
            pnlAddFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddFoodLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAddCart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        pnlAddCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddCartMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlAddCartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAddCartMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 102, 0));
        jLabel24.setText("Tạo Giỏ Hàng Mới");

        javax.swing.GroupLayout pnlAddCartLayout = new javax.swing.GroupLayout(pnlAddCart);
        pnlAddCart.setLayout(pnlAddCartLayout);
        pnlAddCartLayout.setHorizontalGroup(
            pnlAddCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCartLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel24)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pnlAddCartLayout.setVerticalGroup(
            pnlAddCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddCartLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel24)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pnlListFood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlListFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlListFoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlListFoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlListFoodMouseExited(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 51));
        jLabel25.setText("Danh Sách Thực Phẩm");

        javax.swing.GroupLayout pnlListFoodLayout = new javax.swing.GroupLayout(pnlListFood);
        pnlListFood.setLayout(pnlListFoodLayout);
        pnlListFoodLayout.setHorizontalGroup(
            pnlListFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListFoodLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel25)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        pnlListFoodLayout.setVerticalGroup(
            pnlListFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListFoodLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel25)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pnlListCart1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        pnlListCart1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlListCart1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlListCart1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlListCart1MouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 255, 0));
        jLabel26.setText("Danh Sách Giỏ Hàng");

        javax.swing.GroupLayout pnlListCart1Layout = new javax.swing.GroupLayout(pnlListCart1);
        pnlListCart1.setLayout(pnlListCart1Layout);
        pnlListCart1Layout.setHorizontalGroup(
            pnlListCart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListCart1Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(113, 113, 113))
        );
        pnlListCart1Layout.setVerticalGroup(
            pnlListCart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListCart1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel26)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setText("Bạn có thể chọn 1 trong những chức năng sau đây:");

        btnHelp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_help1.png"))); // NOI18N
        btnHelp1.setText("Hướng dẫn sử dụng ");
        btnHelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelp1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(589, 589, 589)
                .addComponent(btnHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(589, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlListFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlAddFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlListCart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlAddCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(41, 41, 41)
                        .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSeach1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnlAddCart, pnlListCart1, pnlListFood});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeach, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnSeach1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlListCart1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlAddCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlAddFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(99, 99, 99)
                        .addComponent(pnlListFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110)
                .addComponent(btnHelp1)
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pnlAddCart, pnlListCart1, pnlListFood});

    }// </editor-fold>//GEN-END:initComponents

    public void defaultLocation() {
        pnlAddFood.setLocation(165, 295);
        pnlAddCart.setLocation(776, 295);
        pnlListFood.setLocation(165, 552);
        pnlListCart1.setLocation(776, 552);
        btnSeach1.setLocation(1028, 72);
    }

    public void changePanel(int a) {
        pnlMain.removeAll();
        if (a == 2 || a == 3 || a == 5) {
            if (a == 2) {
                PaneAddFood panel = (PaneAddFood) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }
            if (a == 3) {
                PaneListFood panel = (PaneListFood) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }
            if (a == 5) {
                PaneListCart panel = (PaneListCart) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }

        } else {
            pnlMain.add(listPanel.get(a));
        }
        pnlMain.updateUI();
        if (a == 1) {
            indexList = 0;
            listIndex.removeAll(listIndex);
            listIndex.add(valueOf(a));
        } else {
            if (Integer.parseInt(listIndex.get(listIndex.size() - 1)) != a) {
                listIndex.add(valueOf(a));
                indexList = listIndex.size() - 1;
            }
        }
        now = a;
    }

    private void pnlAddFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddFoodMouseClicked
        changePanel(2);
    }//GEN-LAST:event_pnlAddFoodMouseClicked

    private void pnlAddCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddCartMouseClicked
        try {
            changePanel(4);
        } catch (Exception ex) {
            Logger.getLogger(PaneHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnlAddCartMouseClicked

    private void pnlListFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListFoodMouseClicked
        changePanel(3);
    }//GEN-LAST:event_pnlListFoodMouseClicked

    private void pnlListCart1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListCart1MouseClicked
        changePanel(5);
    }//GEN-LAST:event_pnlListCart1MouseClicked

    private void btnHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelp1ActionPerformed
        try{
            File f = new File("C:\\Users\\Admin\\Documents\\help.pdf");
            Desktop.getDesktop().open(f);
        }catch (Exception e) {
            e.printStackTrace();
            
        }
    }//GEN-LAST:event_btnHelp1ActionPerformed

    private void btnSeach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeach1ActionPerformed
        search();
    }//GEN-LAST:event_btnSeach1ActionPerformed

    private void txtSeachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSeachKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            search();
        }
    }//GEN-LAST:event_txtSeachKeyPressed

    private void pnlAddFoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddFoodMouseEntered
        jLabel23.setForeground(Color.WHITE);
        pnlAddFood.setSize(498, 152);
        pnlAddFood.setLocation(169, 298);
    }//GEN-LAST:event_pnlAddFoodMouseEntered

    private void pnlAddFoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddFoodMouseExited
        jLabel23.setForeground(new java.awt.Color(51, 51, 255));
        pnlAddFood.setSize(506, 158);
        defaultLocation();
    }//GEN-LAST:event_pnlAddFoodMouseExited

    private void pnlAddCartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddCartMouseEntered
        jLabel24.setForeground(Color.WHITE);
        pnlAddCart.setSize(498, 152);
        pnlAddCart.setLocation(780, 298);
    }//GEN-LAST:event_pnlAddCartMouseEntered

    private void pnlAddCartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddCartMouseExited
        jLabel24.setForeground(new java.awt.Color(255, 102, 0));
        pnlAddCart.setSize(506, 158);
        defaultLocation();
    }//GEN-LAST:event_pnlAddCartMouseExited

    private void pnlListFoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListFoodMouseEntered
        jLabel25.setForeground(Color.WHITE);
        pnlListFood.setSize(498, 152);
        pnlListFood.setLocation(169, 555);
    }//GEN-LAST:event_pnlListFoodMouseEntered

    private void pnlListFoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListFoodMouseExited
        jLabel25.setForeground(new java.awt.Color(255, 255, 51));
        pnlListFood.setSize(506, 158);
        defaultLocation();
    }//GEN-LAST:event_pnlListFoodMouseExited

    private void pnlListCart1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListCart1MouseEntered
        jLabel26.setForeground(Color.WHITE);
        pnlListCart1.setSize(498, 152);
        pnlListCart1.setLocation(780, 555);
    }//GEN-LAST:event_pnlListCart1MouseEntered

    private void pnlListCart1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlListCart1MouseExited
        jLabel26.setForeground(new java.awt.Color(0, 255, 0));
        pnlListCart1.setSize(506, 158);
        defaultLocation();
    }//GEN-LAST:event_pnlListCart1MouseExited

    private void btnSeach1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeach1MouseEntered
        btnSeach1.setSize(133, 38);
        btnSeach1.setLocation(1029, 73);
    }//GEN-LAST:event_btnSeach1MouseEntered

    private void btnSeach1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeach1MouseExited
        btnSeach1.setSize(135, 40);
    }//GEN-LAST:event_btnSeach1MouseExited

    private void search() {
        try {
            String text = txtSeach.getText().toLowerCase().trim();
            int a = 0;

            if (text.contains("giỏ")) {
                GioHangDao dao = new GioHangDao();
                ArrayList<GioHang> list = dao.findAll();
                ArrayList<GioHang> listSearch = new ArrayList<>();
                for (GioHang it : list) {
                    if (it.getTenGioHang().equalsIgnoreCase(text) || it.getMaGioHang().equalsIgnoreCase(text)) {
                        showPanel(it.getMaGioHang(), 4);
                        return;
                    } else {
                        if (it.getTenGioHang().toLowerCase().contains(text)) {
                            listSearch.add(it);
                        }
                    }
                }
                if (listSearch.size() == 0) {
                    MessageDialogHelper.showMessageDialog(this, "Không tìm thấy kết quả cho từ khóa [ " + txtSeach.getText() + " ].", "Thông báo");
                    return;
                }
                PaneSearch panel = new PaneSearch();
                pnlMain.removeAll();
                panel.searchText1(listSearch, txtSeach.getText().trim());
                pnlMain.add(panel);
                pnlMain.updateUI();
                if (Integer.parseInt(listIndex.get(listIndex.size() - 1)) != a) {
                    listIndex.add(valueOf(0));
                    indexList = listIndex.size() - 1;
                }
                now = 0;

            } else {
                ThucPhamDao daotp = new ThucPhamDao();
                ArrayList<ThucPham> list = daotp.findAll();
                ArrayList<ThucPham> listSearch = new ArrayList<>();
                for (ThucPham it : list) {
                    if (it.getTenThucPham().equalsIgnoreCase(text) || it.getMaThucPham().equalsIgnoreCase(text)) {
                        showPanel(it.getMaThucPham(), 2);
                        return;
                    } else {
                        if (it.getTenThucPham().toLowerCase().contains(text) || it.getLoaiThucPham().toLowerCase().contains(text)) {
                            listSearch.add(it);
                        }
                    }
                }
                if (listSearch.size() == 0) {
                    MessageDialogHelper.showMessageDialog(this, "Không tìm thấy kết quả cho từ khóa [ " + txtSeach.getText() + " ].", "Thông báo");
                    return;
                }
                PaneSearch panel = (PaneSearch) listPanel.get(a);
                pnlMain.removeAll();
                panel.searchText(listSearch, txtSeach.getText().trim());
                pnlMain.add(panel);
                pnlMain.updateUI();
                if (Integer.parseInt(listIndex.get(listIndex.size() - 1)) != a) {
                    listIndex.add(valueOf(0));
                    indexList = listIndex.size() - 1;
                }
                now = 0;
            }

        } catch (Exception ex) {
            Logger.getLogger(PaneListFood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showPanel(String id, int a) throws NumberFormatException, Exception {
        pnlMain.removeAll();
        if (a == 4) {
            PaneCreateCart panel = (PaneCreateCart) listPanel.get(4);
            int k = 0;
            for (int i = 0; i < listIndex.size(); i++) {
                if (listIndex.get(i).equals("4")) {
                    k++;
                }
            }
            if (k != 0) {
                panel.createJTabbedPane();
            }
            panel.loadData(id);
            pnlMain.add(panel);
        } else if (a == 2) {
            PaneAddFood panel = (PaneAddFood) listPanel.get(a);
            panel.showThucPham(id);
            pnlMain.add(panel);
        }
        pnlMain.updateUI();
        if (Integer.parseInt(listIndex.get(listIndex.size() - 1)) != a) {
            listIndex.add(valueOf(a));
            indexList = listIndex.size() - 1;
        }
        now = a;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp1;
    private javax.swing.JButton btnSeach1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel pnlAddCart;
    private javax.swing.JPanel pnlAddFood;
    private javax.swing.JPanel pnlListCart1;
    private javax.swing.JPanel pnlListFood;
    private javax.swing.JTextField txtSeach;
    // End of variables declaration//GEN-END:variables
}
