/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewForm;

import dao.GioHangDao;
import dao.KetQuaDao;
import dao.ThucPhamDao;
import helper.MessageDialogHelper;
import java.awt.event.KeyEvent;
import static java.lang.String.valueOf;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import helper.Bang;
import model.GioHang;
import model.KetQua;
import model.ThucPham;
import static viewForm.FrmMain.back;
import static viewForm.FrmMain.indexList;
import static viewForm.FrmMain.listIndex;
import static viewForm.FrmMain.now;
import static viewForm.FrmMain.listPanel;
import static viewForm.FrmMain.pnlMain;
import static viewForm.FrmMain.listPanel;
import static viewForm.FrmMain.pnlMain;

/**
 *
 * @author Admin
 */
public class PaneListCart extends javax.swing.JPanel {

    private Bang table = new Bang();
    private FrmMain parent;

    /**
     * Creates new form PaneListCart
     */
    public PaneListCart() {
        initComponents();
        table.initTableDSGH(tblDSGH);
        loadTable();
    }

    public void loadTable() {
        table.loadDataToTableDSGH(this);
        table.tableModelCart(tblDSGH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cbxSapXep = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSGH = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnXem = new javax.swing.JButton();
        btnEditFood = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        btnReturn = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        btnAddCart = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();

        jPanel1.setBackground(new java.awt.Color(247, 247, 241));

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 102, 0));
        jLabel13.setText("Danh sách Giỏ Hàng");

        cbxSapXep.setBackground(new java.awt.Color(0, 153, 153));
        cbxSapXep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp xếp", "Mới nhất ", "Cũ nhất", "Tối ưu nhất" }));
        cbxSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSapXepActionPerformed(evt);
            }
        });

        tblDSGH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã giỏ hàng", "Tên giỏ hàng", "Tổng giá tiền", "tong gia tri dinh duong", "so tien con lại", "Ngày tạo", "Ghi chú"
            }
        ));
        tblDSGH.setShowGrid(true);
        tblDSGH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblDSGHKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSGH);
        if (tblDSGH.getColumnModel().getColumnCount() > 0) {
            tblDSGH.getColumnModel().getColumn(0).setMinWidth(50);
            tblDSGH.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblDSGH.getColumnModel().getColumn(0).setMaxWidth(50);
            tblDSGH.getColumnModel().getColumn(1).setMinWidth(160);
            tblDSGH.getColumnModel().getColumn(1).setMaxWidth(160);
            tblDSGH.getColumnModel().getColumn(2).setMinWidth(240);
            tblDSGH.getColumnModel().getColumn(2).setMaxWidth(240);
            tblDSGH.getColumnModel().getColumn(3).setMinWidth(180);
            tblDSGH.getColumnModel().getColumn(3).setMaxWidth(180);
            tblDSGH.getColumnModel().getColumn(4).setMinWidth(180);
            tblDSGH.getColumnModel().getColumn(4).setMaxWidth(180);
            tblDSGH.getColumnModel().getColumn(5).setMinWidth(140);
            tblDSGH.getColumnModel().getColumn(5).setMaxWidth(140);
            tblDSGH.getColumnModel().getColumn(6).setMinWidth(140);
            tblDSGH.getColumnModel().getColumn(6).setMaxWidth(140);
            tblDSGH.getColumnModel().getColumn(7).setMinWidth(250);
            tblDSGH.getColumnModel().getColumn(7).setMaxWidth(250);
        }

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sort-descending-icon.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 943, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jToolBar2.setRollover(true);
        jToolBar2.add(jSeparator10);

        jButton2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(135, 32, 32));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Blue-Arrow-Left-icon.png"))); // NOI18N
        jButton2.setText("Trang Trước");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        btnNext.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnNext.setForeground(new java.awt.Color(135, 32, 32));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Green-Arrow-Left-icon.png"))); // NOI18N
        btnNext.setText("Trang Sau");
        btnNext.setFocusable(false);
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextMouseExited(evt);
            }
        });
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jToolBar2.add(btnNext);
        jToolBar2.add(jSeparator1);

        btnXem.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnXem.setForeground(new java.awt.Color(135, 32, 32));
        btnXem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/viewcart-icon.png"))); // NOI18N
        btnXem.setText("Xem");
        btnXem.setFocusable(false);
        btnXem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });
        jToolBar2.add(btnXem);

        btnEditFood.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnEditFood.setForeground(new java.awt.Color(135, 32, 32));
        btnEditFood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editfood-icon.png"))); // NOI18N
        btnEditFood.setText("Cập nhật");
        btnEditFood.setFocusable(false);
        btnEditFood.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditFood.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFoodActionPerformed(evt);
            }
        });
        jToolBar2.add(btnEditFood);

        btnXoa.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(135, 32, 32));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/removefood-icon.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setFocusable(false);
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jToolBar2.add(btnXoa);
        jToolBar2.add(jSeparator11);

        btnReturn.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(135, 32, 32));
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arrow-refresh-icon.png"))); // NOI18N
        btnReturn.setText("Tải Lại");
        btnReturn.setFocusable(false);
        btnReturn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReturn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jToolBar2.add(btnReturn);
        jToolBar2.add(jSeparator13);

        btnAddCart.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnAddCart.setForeground(new java.awt.Color(135, 32, 32));
        btnAddCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_newcart2.png"))); // NOI18N
        btnAddCart.setText("Giỏ Mới");
        btnAddCart.setToolTipText("");
        btnAddCart.setFocusable(false);
        btnAddCart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddCart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAddCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCartActionPerformed(evt);
            }
        });
        jToolBar2.add(btnAddCart);
        jToolBar2.add(jSeparator3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void isNext() {
        if (listIndex.size() == indexList + 1) {
            btnNext.setEnabled(true);
        }
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            int row[] = tblDSGH.getSelectedRows();
            if (row.length == 0) {
                MessageDialogHelper.showMessageDialog(this, "Bạn chưa CHỌN giỏ hàng.", "Thông báo");
                return;
            }
            if (MessageDialogHelper.showConfirmDialog(this, "Bạn có muốn xóa " + row.length + " giỏ hàng này hay không?", "Câu hỏi") == JOptionPane.NO_OPTION) {
                return;
            }
            GioHangDao dao = new GioHangDao();
            StringBuilder sb = new StringBuilder();
            int sus = 0, fail = 0, a = 0;

            for (int i = 0; i < row.length; i++) {
                String id = (String) tblDSGH.getValueAt(row[i], 1);
                KetQuaDao daokq = new KetQuaDao();
                if (daokq.deleteGioHang(id)) {
                    a++;
                }
                if (dao.delete(id)) {
                    sus++;
                } else {
                    fail++;
                }
            }
            if (sus != 0) {
                sb.append(sus + " giỏ hàng đã được XÓA thành công.");
            }
            if (fail != 0) {
                sb.append(fail + " giỏ hàng không được XÓA!");
            }
            loadTable();
            MessageDialogHelper.showMessageDialog(this, sb.toString(), "Thông báo");

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, "Đã xảy ra lôi khi XÓA giỏ hàng!\nBạn hãy thử xóa lại.", "Lỗi");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
        DlogSeeCart secletion;
        try {

            int row = tblDSGH.getSelectedRow();
            if (row < 0) {
                MessageDialogHelper.showMessageDialog(this, "Bạn chưa CHỌN giỏ hàng.", "Thông báo");
                return;
            }
            secletion = new DlogSeeCart(parent, true);
            String id = (String) tblDSGH.getValueAt(row, 1);
            secletion.showGioHang(id);
            secletion.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(PaneListFood.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadTable();
    }//GEN-LAST:event_btnXemActionPerformed

    private void tblDSGHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDSGHKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            DlogSeeCart secletion;
            try {

                int row = tblDSGH.getSelectedRow();
                if (row < 0) {
                    MessageDialogHelper.showMessageDialog(this, "Bạn chưa CHỌN giỏ hàng.", "Thông báo");
                    return;
                }
                secletion = new DlogSeeCart(parent, true);
                String id = (String) tblDSGH.getValueAt(row, 1);
                secletion.showGioHang(id);
                secletion.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(PaneListFood.class.getName()).log(Level.SEVERE, null, ex);
            }
            loadTable();
        }
        if (KeyEvent.VK_DELETE == evt.getKeyCode()) {
            try {
                int row[] = tblDSGH.getSelectedRows();
                if (row.length == 0) {
                    return;
                }
                if (MessageDialogHelper.showConfirmDialog(this, "Bạn có muốn xóa " + row.length + " giỏ hàng này hay không?", "Câu hỏi") == JOptionPane.NO_OPTION) {
                    return;
                }
                GioHangDao dao = new GioHangDao();
                StringBuilder sb = new StringBuilder();
                int sus = 0, fail = 0, a = 0;

                for (int i = 0; i < row.length; i++) {
                    String id = (String) tblDSGH.getValueAt(row[i], 1);
                    KetQuaDao daokq = new KetQuaDao();
                    if (daokq.deleteGioHang(id)) {
                        a++;
                    }
                    if (dao.delete(id)) {
                        sus++;
                    } else {
                        fail++;
                    }
                }
                if (sus != 0) {
                    sb.append(sus + " giỏ hàng đã được XÓA thành công.");
                }
                if (fail != 0) {
                    sb.append(fail + " giỏ hàng không được XÓA!");
                }
                loadTable();
                MessageDialogHelper.showMessageDialog(this, sb.toString(), "Thông báo");

            } catch (Exception e) {
                e.printStackTrace();
                MessageDialogHelper.showErrorDialog(this, "Đã xảy ra lôi khi XÓA giỏ hàng!\nBạn hãy thử xóa lại.", "Lỗi");
            }
        }
    }//GEN-LAST:event_tblDSGHKeyPressed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        loadTable();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnEditFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFoodActionPerformed
        PaneCreateCart panel;
        try {
            int row = tblDSGH.getSelectedRow();
            if (row < 0) {
                MessageDialogHelper.showMessageDialog(this, "Bạn chưa CHỌN giỏ hàng.", "Thông báo");
                return;
            }
            String id = (String) tblDSGH.getValueAt(row, 1);
            panel = (PaneCreateCart) listPanel.get(4);
            pnlMain.removeAll();
            int a = 0;
            for (int i = 0; i < listIndex.size(); i++) {
                if (listIndex.get(i).equals("4")) {
                    a++;
                }
            }
            if (a != 0) {
                panel.createJTabbedPane();
            }
            panel.loadData(id);
            pnlMain.add(panel);
            listPanel.add(this);
            pnlMain.updateUI();
            listIndex.add(valueOf(4));
            indexList = listIndex.size() - 1;
            now = 4;
        } catch (Exception ex) {
            Logger.getLogger(PaneListFood.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditFoodActionPerformed

    private void btnAddCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCartActionPerformed
        PaneCreateCart panel;
        try {
            panel = (PaneCreateCart) listPanel.get(4);
            pnlMain.removeAll();
            int a = 0;
            for (int i = 0; i < listIndex.size(); i++) {
                if (listIndex.get(i).equals("4")) {
                    a++;
                }
            }
            if (a != 0) {
                panel.createJTabbedPane();
            }

            pnlMain.add(panel);
            listPanel.add(this);
            pnlMain.updateUI();
            listIndex.add(valueOf(4));
            indexList = listIndex.size() - 1;
            now = 4;
        } catch (Exception ex) {
            Logger.getLogger(PaneListFood.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnAddCartActionPerformed

    public void sortLatest() throws Exception {
        GioHangDao dao = new GioHangDao();
        ArrayList<GioHang> list = dao.findAll();
        for (int i = 0; i < list.size() - 1; i++) {
            for (int j = 0; j < list.size() - i - 1; j++) {
                int a = 0;
                int y1 = Integer.parseInt(list.get(j).getNgayTao().substring(6));
                int y2 = Integer.parseInt(list.get(j + 1).getNgayTao().substring(6));
                if (y1 >= y2) {
                    int m1 = Integer.parseInt(list.get(j).getNgayTao().substring(3, 5));
                    int m2 = Integer.parseInt(list.get(j + 1).getNgayTao().substring(3, 5));
                    if (m1 >= m2) {
                        int d1 = Integer.parseInt(list.get(j).getNgayTao().substring(0, 2));
                        int d2 = Integer.parseInt(list.get(j + 1).getNgayTao().substring(0, 2));
                        if (d1 < d2) {
                            a++;
                        }
                    } else {
                        a++;
                    }
                } else {
                    a++;
                }

                if (a != 0) {
                    GioHang temp = list.get(j);
                    list.set(j, list.get(j + 1));
                    list.set(j + 1, temp);
                }
            }

        }
        table.loadDataToTableDSGH(this, list);
        table.tableModelCart(tblDSGH);
    }

    public void sortOldest() throws Exception {
        GioHangDao dao = new GioHangDao();
        ArrayList<GioHang> list = dao.findAll();
        for (int i = 0; i < list.size() - 1; i++) {
            for (int j = 0; j < list.size() - i - 1; j++) {
                int a = 0;
                int y1 = Integer.parseInt(list.get(j).getNgayTao().substring(6));
                int y2 = Integer.parseInt(list.get(j + 1).getNgayTao().substring(6));
                if (y1 <= y2) {
                    int m1 = Integer.parseInt(list.get(j).getNgayTao().substring(3, 5));
                    int m2 = Integer.parseInt(list.get(j + 1).getNgayTao().substring(3, 5));
                    if (m1 <= m2) {
                        int d1 = Integer.parseInt(list.get(j).getNgayTao().substring(0, 2));
                        int d2 = Integer.parseInt(list.get(j + 1).getNgayTao().substring(0, 2));
                        if (d1 > d2) {
                            a++;
                        }
                    } else {
                        a++;
                    }
                } else {
                    a++;
                }

                if (a != 0) {
                    GioHang temp = list.get(j);
                    list.set(j, list.get(j + 1));
                    list.set(j + 1, temp);
                }
            }

        }
        table.loadDataToTableDSGH(this, list);
        table.tableModelCart(tblDSGH);
    }

    public void sortTheBest() throws Exception {
        GioHangDao dao = new GioHangDao();
        ArrayList<GioHang> list = dao.findAll();

        for (int i = 0; i < list.size() - 1; i++) {
            for (int j = 0; j < list.size() - i - 1; j++) {
                if (list.get(j).getSoTienCL() > list.get(j + 1).getSoTienCL()) {
                    GioHang temp = list.get(j);
                    list.set(j, list.get(j + 1));
                    list.set(j + 1, temp);
                }
            }

        }
        table.loadDataToTableDSGH(this, list);
        table.tableModelCart(tblDSGH);
    }

    private void cbxSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSapXepActionPerformed
        try {
            if (cbxSapXep.getSelectedIndex() == 0) {
                loadTable();
            }
            if (cbxSapXep.getSelectedIndex() == 1) {
                sortLatest();
            }
            if (cbxSapXep.getSelectedIndex() == 2) {
                sortOldest();
            }
            if (cbxSapXep.getSelectedIndex() == 3) {
                sortTheBest();
            }

        } catch (Exception ex) {
            MessageDialogHelper.showErrorDialog(this, "Đã xảy ra lôi khi xóa thực phẩm!\nBạn hãy thử xóa lại.", "Lỗi");
        }
    }//GEN-LAST:event_cbxSapXepActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pnlMain.removeAll();
        int a = Integer.parseInt(listIndex.get(indexList - 1));
        if (a == 2 || a == 3 || a == 5) {
            if (a == 2) {
                PaneAddFood panel = (PaneAddFood) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }
            if (a == 3) {
                PaneListFood panel = (PaneListFood) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }
            if (a == 5) {
                PaneListCart panel = (PaneListCart) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }

        } else {
            pnlMain.add(listPanel.get(a));
        }
        indexList--;
        if (Integer.parseInt(listIndex.get(indexList)) == 1) {
            listIndex.removeAll(listIndex);
            listIndex.add("1");
            indexList = 0;
        }
        pnlMain.updateUI();
        now = a;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseEntered
        if (listIndex.size() == indexList + 1) {
            btnNext.setEnabled(false);
            btnNext.setToolTipText("Đây là trang cuối cùng!");
        }
    }//GEN-LAST:event_btnNextMouseEntered

    private void btnNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseExited
        btnNext.setEnabled(true);
        btnNext.setToolTipText(null);
    }//GEN-LAST:event_btnNextMouseExited

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (listIndex.size() == indexList + 1) {
            return;
        }
        pnlMain.removeAll();
        int a = Integer.parseInt(listIndex.get(indexList + 1));
        if (a == 2 || a == 3 || a == 5) {
            if (a == 2) {
                PaneAddFood panel = (PaneAddFood) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }
            if (a == 3) {
                PaneListFood panel = (PaneListFood) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }
            if (a == 5) {
                PaneListCart panel = (PaneListCart) listPanel.get(a);
                panel.loadTable();
                pnlMain.add(panel);
            }

        } else {
            pnlMain.add(listPanel.get(a));
        }
        indexList++;
        pnlMain.updateUI();
        now = a;
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCart;
    private javax.swing.JButton btnEditFood;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxSapXep;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTable tblDSGH;
    // End of variables declaration//GEN-END:variables
}
